### ISSUE TITLE
Avoid transfer of files through local memory

### ISSUE THREAD

**Issue by maorfr** [nuvo/skbn#3]
Currently skbn will download a file in its whole to memory, and upload it from memory.
This poses a problem when dealing with large files (larger than the memory resource limit).

Need to investigate if there is another way to go about transferring files without using local memory (or using a pre-determined memory).
Maybe we can stream it from source to destination in some way.

**Comment by maorfr** [comment]
@IvanovOleg let us know once ABS is tested so we can close this issue.
Thanks!

**Comment by IvanovOleg** [comment]
Hi! 1GB file copy k8s -> ABS and ABS -> K8S works fine (tested K8S 1.12.3)

**Comment by maorfr** [comment]
Thanks!
We will close this issue.
https://github.com/nuvo/cain has been updated to use the latest skbn version as well.
